"""
ConstructGuard AI — PDF Report Generator
Generates professional compliance reports using ReportLab.
"""

import os
from pathlib import Path
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image as RLImage, PageBreak, HRFlowable,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

# Output directory for reports
REPORT_DIR = Path(__file__).parent.parent / "output" / "reports"
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# Brand colors
COLOR_PRIMARY = colors.HexColor("#1a1a2e")
COLOR_ACCENT = colors.HexColor("#e94560")
COLOR_SUCCESS = colors.HexColor("#0f9b58")
COLOR_WARNING = colors.HexColor("#f39c12")
COLOR_DANGER = colors.HexColor("#e74c3c")
COLOR_CRITICAL = colors.HexColor("#c0392b")

SEVERITY_COLORS = {
    "critical": COLOR_CRITICAL,
    "high": COLOR_DANGER,
    "medium": COLOR_WARNING,
    "low": COLOR_SUCCESS,
}


def generate_report(
    site_id: str,
    violations: list,
    escalation_info: dict,
    risk_score: float,
    annotated_image_path: str = None,
    original_image_path: str = None,
) -> str:
    """
    Generate a full PDF compliance report.

    Returns:
        Path to the generated PDF file.
    """
    timestamp = datetime.now()
    filename = f"report_{site_id}_{timestamp.strftime('%Y%m%d_%H%M%S')}.pdf"
    output_path = str(REPORT_DIR / filename)

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=25 * mm,
        bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=22,
        textColor=COLOR_PRIMARY,
        spaceAfter=6,
        alignment=TA_CENTER,
    )
    subtitle_style = ParagraphStyle(
        "CustomSubtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.gray,
        alignment=TA_CENTER,
        spaceAfter=20,
    )
    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=COLOR_PRIMARY,
        spaceBefore=16,
        spaceAfter=8,
    )
    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        spaceAfter=6,
    )
    reasoning_style = ParagraphStyle(
        "Reasoning",
        parent=styles["Normal"],
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#555555"),
        leftIndent=15,
        spaceAfter=8,
    )

    elements = []

    # ─── Header ──────────────────────────────────────
    elements.append(Paragraph("🏗️ ConstructGuard AI", title_style))
    elements.append(Paragraph("Construction Site Safety Compliance Report", subtitle_style))
    elements.append(HRFlowable(width="100%", thickness=2, color=COLOR_ACCENT))
    elements.append(Spacer(1, 12))

    # ─── Report Info ─────────────────────────────────
    info_data = [
        ["Site ID:", site_id, "Report Date:", timestamp.strftime("%Y-%m-%d %H:%M")],
        ["Risk Score:", f"{risk_score:.1f}/100", "Escalation:", escalation_info.get("escalation_level", "normal").upper()],
        ["Total Violations:", str(len(violations)), "Generated By:", "ConstructGuard AI v3.0"],
    ]
    info_table = Table(info_data, colWidths=[90, 140, 100, 140])
    info_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), COLOR_PRIMARY),
        ("TEXTCOLOR", (2, 0), (2, -1), COLOR_PRIMARY),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(info_table)
    elements.append(Spacer(1, 16))

    # ─── Annotated Image ─────────────────────────────
    img_path = annotated_image_path or original_image_path
    if img_path and os.path.exists(img_path):
        elements.append(Paragraph("Site Analysis — Annotated View", heading_style))
        try:
            img = RLImage(img_path, width=6 * inch, height=4 * inch)
            img.hAlign = "CENTER"
            elements.append(img)
            elements.append(Spacer(1, 8))
        except Exception:
            elements.append(Paragraph("(Image could not be loaded)", body_style))

    # ─── Escalation Status ───────────────────────────
    esc_level = escalation_info.get("escalation_level", "normal")
    esc_message = escalation_info.get("message", "")
    if esc_level != "normal":
        elements.append(Paragraph("⚠️ Escalation Alert", heading_style))
        elements.append(Paragraph(esc_message, body_style))
        elements.append(Spacer(1, 8))

    # ─── Violations Detail ───────────────────────────
    elements.append(Paragraph("Violation Details", heading_style))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
    elements.append(Spacer(1, 6))

    if not violations:
        elements.append(Paragraph("✅ No safety violations detected. Site is compliant.", body_style))
    else:
        for i, v in enumerate(violations, 1):
            vtype = v.get("violation_type", v.get("type", "Unknown"))
            severity = v.get("severity", "medium")
            location = v.get("location", "Unknown location")
            reasoning = v.get("reasoning", "No additional context.")
            confidence = v.get("confidence", 0)

            sev_color = SEVERITY_COLORS.get(severity, colors.gray)

            # Violation header
            header_text = f"<b>#{i} — {vtype.replace('_', ' ').upper()}</b>"
            elements.append(Paragraph(header_text, ParagraphStyle(
                "ViolHead", parent=body_style, fontSize=11, textColor=sev_color,
            )))

            # Violation details table
            detail_data = [
                ["Severity:", severity.upper(), "Location:", location],
            ]
            if confidence > 0:
                detail_data.append(["Confidence:", f"{confidence:.0%}", "", ""])

            detail_table = Table(detail_data, colWidths=[70, 130, 70, 200])
            detail_table.setStyle(TableStyle([
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
                ("TOPPADDING", (0, 0), (-1, -1), 2),
            ]))
            elements.append(detail_table)

            # Reasoning
            elements.append(Paragraph(f"<i>Analysis: {reasoning}</i>", reasoning_style))
            elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#eeeeee")))
            elements.append(Spacer(1, 4))

    # ─── Summary ─────────────────────────────────────
    elements.append(Spacer(1, 16))
    elements.append(Paragraph("Summary & Recommendations", heading_style))

    critical_count = sum(1 for v in violations if v.get("severity") == "critical")
    high_count = sum(1 for v in violations if v.get("severity") == "high")

    if critical_count > 0:
        elements.append(Paragraph(
            f"⛔ {critical_count} critical violation(s) require immediate corrective action. "
            f"Stop-work orders should be issued for affected zones until compliance is verified.",
            body_style
        ))
    if high_count > 0:
        elements.append(Paragraph(
            f"⚠️ {high_count} high-severity violation(s) require supervisor attention within 1 hour.",
            body_style
        ))
    if not violations:
        elements.append(Paragraph("All workers appear to be in compliance with safety regulations.", body_style))

    # ─── Footer ──────────────────────────────────────
    elements.append(Spacer(1, 30))
    elements.append(HRFlowable(width="100%", thickness=1, color=COLOR_ACCENT))
    elements.append(Paragraph(
        "Generated by ConstructGuard AI v3.0 — AMD MI300X + Qwen3.6-27B  |  "
        f"Report ID: {site_id}-{timestamp.strftime('%Y%m%d%H%M%S')}",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=7,
                       textColor=colors.gray, alignment=TA_CENTER, spaceBefore=6)
    ))

    # Build PDF
    doc.build(elements)
    return output_path
